dataset_config:
  dataset_split:
    train: [
      "dendrites3dtrain"
    ]
    validation: [
      "dendrites3dvalidation",
    ]
    test: [
      "dendrites3dtest",
    ]
  stack_downsampling:
    type: 'None' # 'None', 'random', 'linear', 'from_start', 'from_end'
#    frac: 1.0
    # number_of_images: 1
    num_skip_beg_slices: 0 # trims n slices off of beginning of stack with N total slices. Slice n+1 becomes new Slice 1
    num_skip_end_slices: 0 # trims m slices off of end of stack with N total slices. Slice N-(m+1) becomes new last slice
  target_size: [512, 512]
  image_cropping:
    type: 'None' # 'None', 'random'
    num_per_image: 1 # 1 is all that is supported at the moment
  class_annotation_mapping:
    class_0_annotation_GVs: [100, 175, 250]  # '0-degree_damage', '45-degree_damage', '90-degree_damage' #NOT USED
